---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-demo
  namespace: default
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/FlexShopper/flux-demo

