---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: install-cluster-aws-chart
  namespace: default
spec:
  chart:
    spec:
      chart: ./03-cluster-aws
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-demo
        namespace: default
  interval: 15s
  serviceAccountName: automation

