apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  annotations:
    giantswarm.io/docs: https://docs.giantswarm.io/ui-api/management-api/crd/machinedeployments.cluster.x-k8s.io/
  labels:
    cluster-operator.giantswarm.io/version: ""
    cluster.x-k8s.io/cluster-name: {{ .Values.clusterid }}
    giantswarm.io/cluster: {{ .Values.clusterid }}
    giantswarm.io/machine-deployment: {{ .Values.nodepooleid }}
    giantswarm.io/organization: {{ .Values.organization }}
    release.giantswarm.io/version: ""
  name: {{ .Values.nodepooleid }}
  namespace: {{ .Values.namespace }}
spec:
  clusterName: {{ .Values.clusterid }}
  selector: {}
  template:
    metadata: {}
    spec:
      bootstrap: {}
      clusterName: {{ .Values.clusterid }}
      infrastructureRef:
        apiVersion: infrastructure.giantswarm.io/v1alpha3
        kind: AWSMachineDeployment
        name: {{ .Values.nodepooleid }}
        namespace: {{ .Values.namespace }}
status: {}
---
apiVersion: infrastructure.giantswarm.io/v1alpha3
kind: AWSMachineDeployment
metadata:
  annotations:
    giantswarm.io/docs: https://docs.giantswarm.io/ui-api/management-api/crd/awsmachinedeployments.infrastructure.giantswarm.io/
  labels:
    aws-operator.giantswarm.io/version: 11.10.0
    cluster.x-k8s.io/cluster-name: {{ .Values.clusterid }}
    giantswarm.io/cluster: {{ .Values.clusterid }}
    giantswarm.io/machine-deployment: {{ .Values.nodepooleid }}
    giantswarm.io/organization: {{ .Values.organization }}
    release.giantswarm.io/version: 17.3.3
  name: {{ .Values.nodepooleid }}
  namespace: {{ .Values.namespace }}
spec:
  nodePool:
    description: {{ .Values.clusterid }}
    machine:
      dockerVolumeSizeGB: 100
      kubeletVolumeSizeGB: 100
    scaling:
      max: 2
      min: 1
  provider:
    availabilityZones:
    - {{ .Values.availabilityzone }}
    instanceDistribution:
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 100
    worker:
      instanceType: {{ .Values.nodetype }}
      useAlikeInstanceTypes: false
status:
  provider:
    worker: {}
